designs:
  sydney36cr:
    canonicalName: "Sydney 36 CR"
    aliases:
    - "Sydney 36 OD"
  customplym61:
    canonicalName: "Custom Plym 61"
    aliases:
    - "Custom timber sloop built by Plym boatbuilders in Sweden 61 Square Meter designed\
      \ by E Salander"
    - "customtimbersloopbuiltbyplymboatbuildersinsweden61squaremetredesignedbyesalander"
  "29er":
    canonicalName: null
    aliases:
    - "29er 29er"
    - "29er29er"
  beneteaufirst407:
    canonicalName: "Beneteau First 40.7"
    aliases:
    - "FIRST 40.7"
    - "first407"
  beneteaufirst477:
    canonicalName: "Beneteau First 47.7"
    aliases:
    - "FIRST 47.7"
    - "first477"
  beneteaufirst447:
    canonicalName: "Beneteau First 44.7"
    aliases:
    - "FIRST 44.7"
    - "first447"
  beneteaufirst347:
    canonicalName: "Beneteau First 34.7"
    aliases:
    - "FIRST 34.7"
    - "first347"
  beneteaufirst337:
    canonicalName: "Beneteau First 33.7"
    aliases:
    - "FIRST 33.7"
    - "first337"
  beneteaufirst367:
    canonicalName: "Beneteau First 36.7"
    aliases:
    - "FIRST 36.7"
    - "first367"
  archambaultgrandsurprise:
    canonicalName: "Archambault Grand Surprise"
    aliases:
    - "Archambault 32"
    - "archambault32"
  beneteaufirst50:
    canonicalName: "Beneteau First 50"
    aliases:
    - "FIRST 50"
    - "first50"
  beneteaufirst45:
    canonicalName: "Beneteau First 45"
    aliases:
    - "FIRST 45"
    - "first45"
  beneteaufirst40:
    canonicalName: "Beneteau First 40"
    aliases:
    - "FIRST 40"
    - "first40"
  beneteaufirst35:
    canonicalName: "Beneteau First 35"
    aliases:
    - "FIRST 35"
    - "first35"
  beneteaufirst53:
    canonicalName: "Beneteau First 53"
    aliases:
    - "FIRST YACHT 53"
    - "firstyacht53"
  beneteaufirst305:
    canonicalName: "Beneteau First 305"
    aliases:
    - "First 305"
    - "first305"
  beneteaufirst30:
    canonicalName: "Beneteau First 30"
    aliases:
    - "FIRST 30 (2010)"
    - "first302010"
  beneteaufirst325:
    canonicalName: "Beneteau First 325"
    aliases:
    - "First 325"
    - "first325"
  beneteaufirst345:
    canonicalName: "Beneteau First 345"
    aliases:
    - "FIRST 345"
    - "first345"
  jeanneausunfast3300:
    canonicalName: "Jeanneau Sunfast 3300"
    aliases:
    - "SUN FAST 3300"
    - "sunfast3300"
  jeanneausunfast3600:
    canonicalName: "Jeanneau Sun Fast 3600"
    aliases:
    - "SUN FAST 3600"
    - "sunfast3600"
  jeanneausunfast3200:
    canonicalName: "Jeanneau Sunfast 3200"
    aliases:
    - "SUN FAST 3200"
    - "sunfast3200"
  sydney38:
    canonicalName: "SYDNEY 38"
    aliases:
    - "Sydney Yachts Sydney 38"
    - "sydneyyachtssydney38"
  yngling:
    canonicalName: "Yngling"
    aliases:
    - "Sunburst Yngling"
    - "sunburstyngling"
  j24:
    canonicalName: "J 24"
    aliases:
    - "J24 J24"
    - "j24j24"
    - "Jarkan J24"
    - "jarkanj24"
    - "J Boats J24"
    - "jboatsj24"
    - "Bashford J24"
    - "bashfordj24"
    - "J 24 ORC Only"
    - "j24orconly"
  jboatsj122:
    canonicalName: "J Boats J/122"
    aliases:
    - "J122"
  jboatsj111:
    canonicalName: "J Boats J/111"
    aliases:
    - "J 111"
    - "j111"
  jboatsj80:
    canonicalName: "J Boats J/80"
    aliases:
    - "J/80 J/80"
    - "j80j80"
    - "J 80"
    - "j80"
  jboatsj70:
    canonicalName: "J Boats J/70"
    aliases:
    - "J70"
  jboatsj99:
    canonicalName: "J Boats J/99"
    aliases:
    - "J 99"
    - "j99"
  jboatsj100:
    canonicalName: "J Boats J/100"
    aliases:
    - "J 100"
    - "j100"
  jboatsj109:
    canonicalName: "J Boats J/109"
    aliases:
    - "J109"
  jboatsj112e:
    canonicalName: "J Boats J/112E"
    aliases:
    - "J 112e"
    - "j112e"
  jboatsj130:
    canonicalName: "J Boats J/130"
    aliases:
    - "J/130"
    - "j130"
  jboatsj133:
    canonicalName: "J Boats J/133"
    aliases:
    - "J 133"
    - "j133"
  jboatsj35:
    canonicalName: "J Boats J35"
    aliases:
    - "J 35"
    - "j35"
  jboatsj88:
    canonicalName: "J Boats J/88"
    aliases:
    - "J 88"
    - "j88"
  jboatsj97:
    canonicalName: "J Boats J/97"
    aliases:
    - "J 97"
    - "j97"
  adams10:
    canonicalName: "ADAMS 10"
    aliases:
    - "Adams 10 Adams 10 racing"
    - "adams10adams10racing"
  openbic:
    canonicalName: "O'Pen Bic"
    aliases:
    - "Bic Open Skiff"
    - "bicopenskiff"
    - "Bic Open Bic"
    - "bicopenbic"
  opti:
    canonicalName: "Opti"
    aliases:
    - "Maclaughlin Optimist"
    - "maclaughlinoptimist"
    - "Mccloughlan Optimist"
    - "mccloughlanoptimist"
  bashfordsydney36:
    canonicalName: "BASHFORD (SYDNEY) 36"
    aliases:
    - "Bashford Howison 36"
    - "bashfordhowison36"
  flyingtiger10:
    canonicalName: "FLYING TIGER 10"
    aliases:
    - "Flying Tiger"
    - "flyingtiger"
  farr30od:
    canonicalName: "FARR 30 OD"
    aliases:
    - "Mumm 30"
    - "mumm30"
  farr36:
    canonicalName: "FARR 36"
    aliases:
    - "MUMM 36"
    - "mumm36"
  sydney36:
    canonicalName: "Sydney 36"
    aliases:
    - "Sydney36mkI"
  sydney36mkII:
    canonicalName: "Sydney 36 mkII"
    aliases:
      - "Sydney36mk2"

boats:
  day_dreaming:
    canonicalName: "Day Dreaming"
    canonicalSailNumber: "MYC7"
    aliases:
    - name: "1060"
      from: null
      until: "2026-01-01"
    - name: "TenSixty"
      from: null
      until: "2026-01-01"
    altSailNumbers: []
  navy_one:
    canonicalName: "Navy One"
    canonicalSailNumber: "0404"
    aliases:
    - name: "Navy One"
      from: null
      until: null
    - name: "B Navy One"
      from: null
      until: null
    - name: "NAVY ONE"
      from: null
      until: null
    altSailNumbers:
    - number: "040"
      from: null
      until: null
  gweilo:
    canonicalName: "Gweilo"
    canonicalSailNumber: "052"
    aliases:
    - name: "Gweilo"
      from: null
      until: null
    altSailNumbers: []
  norton_white_corum:
    canonicalName: "Norton White Corum"
    canonicalSailNumber: "1088"
    aliases:
    - name: "CORUM"
      from: null
      until: null
    altSailNumbers: []
  wild_thing:
    canonicalName: "Wild Thing"
    canonicalSailNumber: "1014"
    aliases:
    - name: "UBS Wild Thing"
      from: null
      until: null
    - name: "Tribeca Wild Thing"
      from: null
      until: null
    altSailNumbers: []
  cheeky:
    canonicalName: "Cheeky"
    canonicalSailNumber: "2499"
    aliases:
    - name: "Rhianon"
      from: null
      until: null
    - name: "Cheeky"
      from: null
      until: null
    altSailNumbers:
    - number: "1956"
      from: null
      until: null
  rising_sun:
    canonicalName: "Rising Sun"
    canonicalSailNumber: "ASC1"
    aliases:
    - name: "Rising Sun"
      from: null
      until: null
    altSailNumbers: []
  much_ado_v:
    canonicalName: "MUCH ADO V"
    canonicalSailNumber: "11978"
    aliases:
    - name: "Much Ado V"
      from: null
      until: null
    altSailNumbers: []
  local_hero:
    canonicalName: "LOCAL HERO"
    canonicalSailNumber: "1236"
    aliases:
    - name: "Local Hero"
      from: null
      until: null
    altSailNumbers: []
  jupiter:
    canonicalName: "Jupiter"
    canonicalSailNumber: "MYC99"
    aliases:
    - name: "Jupiter (DH)"
      from: null
      until: null
    altSailNumbers: []
  joss:
    canonicalName: "Joss"
    canonicalSailNumber: "MYC10"
    aliases:
    - name: "Joss"
      from: null
      until: null
    altSailNumbers:
    - number: "RF177"
      from: null
      until: null
  maxishambles:
    canonicalName: "MAXISHAMBLES"
    canonicalSailNumber: "335"
    aliases:
    - name: "MAXISHAMBLES"
      from: null
      until: null
    altSailNumbers:
    - number: "335TBA"
      from: null
      until: null
  maxishambles-beneteaufirst40:
    canonicalName: "MAXISHAMBLES"
    canonicalSailNumber: "2472"
    aliases:
    - name: "MAXISHAMBLES"
      from: null
      until: null
    altSailNumbers:
    - number: "335"
      from: null
      until: null
    - number: "335TBA"
      from: null
      until: null
  omnishambles-farr30od:
    canonicalName: "OMNISHAMBLES"
    canonicalSailNumber: "SU150"
    aliases:
    - name: "OMNISHAMBLES"
      from: null
      until: null
    altSailNumbers:
    - number: "SM150"
      from: null
      until: null
  wings_of_fire-optimistopen:
    canonicalName: "Wings of Fire"
    canonicalSailNumber: "AUS1797"
    aliases:
    - name: "Wings of Fire"
      from: null
      until: null
    altSailNumbers:
    - number: "AUS1791"
      from: null
      until: null
  vivacite-d3:
    canonicalName: "VIVACITE"
    canonicalSailNumber: "G5"
    aliases:
    - name: "VIVACITE"
      from: null
      until: null
    altSailNumbers:
    - number: "5"
      from: null
      until: null
  the_usual_suspects-d1:
    canonicalName: "THE USUAL SUSPECTS"
    canonicalSailNumber: "G6525"
    aliases:
    - name: "THE USUAL SUSPECTS"
      from: null
      until: null
    altSailNumbers:
    - number: "6525"
      from: null
      until: null
  comanche-vplpverdiermaxi100ft:
    canonicalName: "Comanche"
    canonicalSailNumber: "CAY007"
    aliases:
    - name: "Andoo Comanche"
      from: null
      until: null
    - name: "Master Lock Comanche"
      from: null
      until: null
    altSailNumbers: []
  hamilton_island_wild_oats:
    canonicalName: "HAMILTON ISLAND WILD OATS"
    canonicalSailNumber: "AUS10001"
    aliases:
    - name: "Hamilton Island Wild Oats"
      from: null
      until: null
    altSailNumbers:
    - number: "10001"
      from: null
      until: null
  no_limit-reichelpugh63:
    canonicalName: "No Limit"
    canonicalSailNumber: "AUS98888"
    aliases:
    - name: "No Limit"
      from: null
      until: null
    altSailNumbers:
    - number: "98888"
      from: null
      until: null
  celestial-tp52:
    canonicalName: "Celestial"
    canonicalSailNumber: "SM9535"
    aliases:
    - name: "Celestial"
      from: null
      until: null
    altSailNumbers:
    - number: "9535"
      from: null
      until: null
  another_planet-sydney36cr:
    canonicalName: "Another Planet"
    canonicalSailNumber: "YC521"
    aliases:
    - name: "ANOTHER PLANET"
      from: null
      until: null
    altSailNumbers:
    - number: "521"
      from: null
      until: null
  wild_thing_100-supermaxi:
    canonicalName: "Wild Thing 100"
    canonicalSailNumber: "AUS1001"
    aliases:
    - name: "Wild Thing 100"
      from: null
      until: null
    altSailNumbers: []
  wild_oats_x-reichelpugh66:
    canonicalName: "Wild Oats X"
    canonicalSailNumber: "7001"
    aliases:
    - name: "Wild Oats X"
      from: null
      until: null
    altSailNumbers: []
  wild_oats_x:
    canonicalName: "WILD OATS X"
    canonicalSailNumber: "AUS7001"
    aliases:
    - name: "Wild Oats X"
      from: null
      until: null
    altSailNumbers:
    - number: "7001"
      from: null
      until: null
  esprit-archambaultgrandsurprise:
    canonicalName: "Esprit"
    canonicalSailNumber: "MYC32"
    aliases:
    - name: "Esprit"
      from: null
      until: null
    altSailNumbers: []
  bazinga-archambaultgrandsurprise:
    canonicalName: "Bazinga"
    canonicalSailNumber: "N16"
    aliases:
    - name: "Bazinga"
      from: null
      until: null
    altSailNumbers: []
  remedy-archambaultgrandsurprise:
    canonicalName: "Remedy"
    canonicalSailNumber: "M2"
    aliases:
    - name: "Remedy"
      from: null
      until: null
    altSailNumbers: []
  solace-jeanneauso409:
    canonicalName: "Solace"
    canonicalSailNumber: "MYC409"
    aliases:
    - name: "Manly Sailing SOLACE"
      from: null
      until: null
    altSailNumbers: []
  alive:
    canonicalName: "Alive"
    canonicalSailNumber: "AUS52566"
    aliases:
    - name: "Alive"
      from: null
      until: null
    altSailNumbers:
    - number: "52566"
      from: null
      until: null
  absolut-archambaulta35:
    canonicalName: "Absolut"
    canonicalSailNumber: "R350"
    aliases:
    - name: "Absolut"
      from: null
      until: null
    altSailNumbers:
    - number: "A350"
      from: null
      until: null
  okavango_delta-j24:
    canonicalName: "Okavango Delta"
    canonicalSailNumber: "JAUS44361AUS4788"
    aliases:
    - name: "Okavango Delta"
      from: null
      until: null
    altSailNumbers:
    - number: "4436"
      from: null
      until: null
    - number: "AUS4437"
      from: null
      until: null
    - number: "JAUS44361"
      from: null
      until: null
    - number: "JAUS44364437"
      from: null
      until: null
    - number: "JAUS4788"
      from: null
      until: null
    - number: "JAUS443614437"
      from: null
      until: null
  stock_car-j24:
    canonicalName: "Stock Car"
    canonicalSailNumber: "AUS4475"
    aliases:
    - name: "Stock Car"
      from: null
      until: null
    altSailNumbers:
    - number: "AUS144"
      from: null
      until: null
    - number: "JAUS154"
      from: null
      until: null
    - number: "JAUS4475"
      from: null
      until: null
  kaotic-j24:
    canonicalName: "Kaotic"
    canonicalSailNumber: "AUS4770"
    aliases:
    - name: "Kaotic"
      from: null
      until: null
    altSailNumbers:
    - number: "JAUS4770"
      from: null
      until: null
  daybreak-palmerjohnsonnewyork40:
    canonicalName: "Daybreak"
    canonicalSailNumber: "MYC9"
    aliases:
    - name: "Daybreak"
      from: null
      until: null
    altSailNumbers:
    - number: "26996"
      from: null
      until: null
  sirius-adams10:
    canonicalName: "Sirius"
    canonicalSailNumber: "MH118"
    aliases:
    - name: "Sirius"
      from: null
      until: null
    altSailNumbers:
    - number: "B363"
      from: null
      until: null
    - number: "MYC9"
      from: null
      until: null
  waterhound-j24:
    canonicalName: "Waterhound"
    canonicalSailNumber: "JAUS4434"
    aliases:
    - name: "Waterhound"
      from: null
      until: null
    altSailNumbers:
    - number: "4434"
      from: null
      until: null
  savannah_girl-swan46:
    canonicalName: "Savannah Girl"
    canonicalSailNumber: "46075"
    aliases:
    - name: "Savannah Girl"
      from: null
      until: null
    altSailNumbers:
    - number: "40675"
      from: null
      until: null
  philosopher-sydney36cr:
    canonicalName: "Philosopher"
    canonicalSailNumber: "020"
    aliases:
    - name: "Philosopher"
      from: null
      until: null
    altSailNumbers:
    - number: "20"
      from: null
      until: null
  aileron-sydney36cr:
    canonicalName: "Aileron"
    canonicalSailNumber: "R6785"
    aliases:
    - name: "Aileron"
      from: null
      until: null
    altSailNumbers:
    - number: "6785"
      from: null
      until: null
  impulse-sydney36cr:
    canonicalName: "Impulse"
    canonicalSailNumber: "8777"
    aliases:
    - name: "Impulse"
      from: null
      until: null
    altSailNumbers:
    - number: "002"
      from: null
      until: null
  sea_change-sydney36cr:
    canonicalName: "Sea Change"
    canonicalSailNumber: "5879"
    aliases:
    - name: "Sea Change"
      from: null
      until: null
    altSailNumbers:
    - number: "SEA"
      from: null
      until: null
sailNumberRedirects: {}
