# IMPORTANT: This file is managed by the server.
# It is overwritten whenever exclusions are changed via the admin UI.
# Only edit manually when the server is NOT running.

boats: []
designs:
- ''
- barrinkpodcat
- foilboard
- nacra
- tp52duplicateboatforlateorcientrydonotuse
- fonekitefoil
- hhcatamarans44
- aero12
- starboardseverneolympiciqfoilclass
- kitefoilfoil
- nacraf16
- nacraf18
- taipan49
- marstromm20notatornadoascatamaranyardstick62
- testerfinn
- andrewstransky50catamaransevenseas50
- viperconvertiblefoiler
- rsaero5
- nacraf18infusionmk1
- patrikfoilcomp100v2
- wingfoil
- rsaero9
- toolaclasscatamaran
- wildcat
- orcduplicateentry
- international14ftskiff
- maricat43
- test
- ovingtonmustoskiff
- dnaf1xfoilingf1x
- iqfoil95
- starboardiqfoil95
- rsaero
- exploderaclasscatamaran
- aclassfoil
- schioning1320waterlinecatamaran
- beneteaufirst40duplicateboatforlateircentrydonotuse
- cfoil
- international14ftskiffbeiker6
- offthebeachcatamaranpapertiger
- c2
- mosquitocat
- donotuseduplicateboatcreatedforlateircentry
- mustoskiffmustoskiff
- aclasscatamaranvintagegeltekflyerii
- mothfoiler
- windrushcat14
- iqfoiljunior
- wing
- goodallakurra
- ovingtonokdinghy
- aaa
- kitefoilkitefoilaustralia
- windfoilboard
- iqfoil
- mirror
- dinghysport
- catrig1uptraphobie14
- lightwavecatamaranlightwave38
- starboardiqfoil
- open85cat
- asiacatamaranstealth1260
- iqfoilyouth
- aero
- optimistopen
- formulafoil
- orcduplicate
- lightwave46catamaran
- northwingfoil
- nacracarbon20nonfoiling
- asiacatamaransstealth125
- testyacht
- goodallc2
- starboardiqyouthfoil
- starboardiqfoilyouth
- taipan49catrigonlynokite
- windrush
- goodalldesignc2f18
- windrushsurfcat12
- aero7
- formula18catamaran
- aluminiumcataluminiumcat
- mackayicebreakerokdinghy
- bluemagicoptimist
- jboats
- raceboard
- lynx88catamaran
- sailboard
- arber38catsoutheaster
- hobiewildcat
- delfokdinghy
- gbecat
- aero9
- dinghysports
- marstromextreme40
- customf28
- marstromm32
- gc32
races: []
series:
- \botb\b
- off the beach
- \bskiff\b
- foil
- \bdinghy
- \bfinn\b
- \baero\b
- \binternational ok\b
