excluded:
- "12ft skiff"
- "13ft skiff"
- "16ft skiff"
- "18ft skiff"
- "29er"
- "420"
- "470"
- "49er"
- "505"
- "79er"
- "a class catamaran"
- "aaa"
- "aclasscatamaranvintagegeltekflyerii"
- "aclassfoil"
- "aero"
- "aero12"
- "aero7"
- "aero9"
- "aluminiumcataluminiumcat"
- "andrewstransky50catamaransevenseas50"
- "arber38catsoutheaster"
- "arrow"
- "asiacatamaransstealth125"
- "asiacatamaranstealth1260"
- "b14"
- "barrinkpodcat"
- "beneteaufirst40duplicateboatforlateircentrydonotuse"
- "blazer"
- "bluemagicoptimist"
- "c2"
- "catrig1uptraphobie14"
- "cfoil"
- "cherub"
- "contender"
- "customf28"
- "delfokdinghy"
- "dinghy"
- "dinghysport"
- "dinghysports"
- "dnaf1xfoilingf1x"
- "donotuseduplicateboatcreatedforlateircentry"
- "exploderaclasscatamaran"
- "f16"
- "f18"
- "feva xl"
- "finn"
- "flying 11"
- "flying ant"
- "foilboard"
- "fonekitefoil"
- "formula18catamaran"
- "formulafoil"
- "gbecat"
- "gc32"
- "goodallakurra"
- "goodallc2"
- "goodalldesignc2f18"
- "heron"
- "hhcatamarans44"
- "historic 18 foot skiffs"
- "hobie 14 turbo"
- "hobie 14"
- "hobie 16"
- "hobie 17"
- "hobie 18"
- "hobiewildcat"
- "ilca 4"
- "ilca 6"
- "ilca 7"
- "international 14"
- "international cadet"
- "international canoe"
- "international moth"
- "international14ftskiff"
- "international14ftskiffbeiker6"
- "iqfoil"
- "iqfoil95"
- "iqfoiljunior"
- "iqfoilyouth"
- "javelin"
- "kitefoilfoil"
- "kitefoilkitefoilaustralia"
- "laser"
- "lightwave46catamaran"
- "lightwavecatamaranlightwave38"
- "lynx88catamaran"
- "mackayicebreakerokdinghy"
- "maricat43"
- "marstromextreme40"
- "marstromm20notatornadoascatamaranyardstick62"
- "marstromm32"
- "minnow"
- "mirror"
- "mosquito"
- "mosquitocat"
- "mothfoiler"
- "musto skiff"
- "mustoskiffmustoskiff"
- "nacra 16"
- "nacra 17"
- "nacra 4.5"
- "nacra"
- "nacracarbon20nonfoiling"
- "nacraf16"
- "nacraf18"
- "nacraf18infusionmk1"
- "northwingfoil"
- "ns14"
- "open skiff"
- "offthebeachcatamaranpapertiger"
- "ok dinghy"
- "open85cat"
- "optimist"
- "optimistopen"
- "orcduplicate"
- "orcduplicateentry"
- "ovingtonmustoskiff"
- "ovingtonokdinghy"
- "pacer"
- "paper tiger"
- "patrikfoilcomp100v2"
- "pittwater junior"
- "raceboard"
- "rs aero 6"
- "rs aero 7"
- "rs feva"
- "rs quest"
- "rs100 8.4"
- "rs200"
- "rs800"
- "rsaero"
- "rsaero5"
- "rsaero9"
- "sabot"
- "sailboard"
- "sailfish"
- "schioning1320waterlinecatamaran"
- "scow moth"
- "sharpie"
- "skate"
- "skud 18"
- "spiral"
- "starboardiqfoil"
- "starboardiqfoil95"
- "starboardiqfoilyouth"
- "starboardiqyouthfoil"
- "starboardseverneolympiciqfoilclass"
- "taipan49"
- "taipan49catrigonlynokite"
- "tasar"
- "test"
- "testerfinn"
- "testing"
- "testtest"
- "testyacht"
- "toolaclasscatamaran"
- "tp52duplicateboatforlateorcientrydonotuse"
- "viperconvertiblefoiler"
- "waszp"
- "wildcat"
- "windfoil"
- "windfoilboard"
- "windrush"
- "windrushcat14"
- "windrushsurfcat12"
- "windsurfer"
- "wing"
- "wingfoil"
- "compassyachtsnzdavidson31"
- "intercarenebalanzone30"
- "wright10nz"
- "125"
- "167095"
- "weta"
- "donotuse"
- "openbic"
- "farriertrimaranf32srcx"
- "farriertrimaran85sr"
- "browntrimaran41"
- "burgessb10trimaran"
- "crowthertrimaran36ft"
- "diam24trimiran"
- "farrier32axtrimaran"
- "graingertrimaran"
- "graingertrimaran075"
- "trimaranavalon9"
- "trimaranirens12"
- "tp52donotuseordamendmentonly"
- "corby49notforentryduplicateboatforlateircentrydonotusegoingforward"
ignored:
- "adams"
- "bavaria"
- "beneteau"
- "catalina"
- "catamaran"
- "classic sloop"
- "cruiser racer"
- "cruiser"
- "cutter"
- "d1"
- "d10"
- "d11"
- "d12"
- "d123"
- "d13"
- "d14"
- "d15"
- "d16"
- "d17"
- "d18"
- "d19"
- "d2"
- "d20"
- "d21"
- "d22"
- "d23"
- "d24"
- "d25"
- "d26"
- "d27"
- "d28"
- "d29"
- "d3"
- "d30"
- "d4"
- "d5"
- "d6"
- "d7"
- "d8"
- "d9"
- "dufour"
- "elan"
- "hanse"
- "hunter"
- "jboat"
- "jboats"
- "jeanneau"
- "keelboat"
- "ketch"
- "monohull"
- "motor sailer"
- "motorsailer"
- "multihull"
- "racer"
- "sailing yacht"
- "sloop"
- "trimaran"
- "xyacht"
- "yacht"
- "yawl"
- "beneteausense"
- "adamsradford"
- "beashelcuttersloop"
- "bennett"
- "bethwaite"
- "bermudiansloop"
- "bermudancutter"
- "boyer"
- "boxboat"
- "bragg"
- "brolga"
- "brresen"
- "camperandnicholsonsloop"
- "tt"
- "pretendfast"
- "ty56789"
- "fororcratingpurposeonlydonotenter"
- "gaffcutter"
- "raider"
- "griffincrown"
- "colleen"
- "netboat"
- "melco"
- "randallcustom"
- "orcratingchangeonlydonotuse"
- "gaffschooner"
- "customcustom"
- "illingworth"
- "mcdonald"
- "rangergaffcutter"
- "gaffriggedtrailersailer"
- "martenindustries"
- "sydneyharbourcoachhousecruiserhayespeeldesign"
- "contessa"
- "young"
- "crowthersupershockwave"
- "elliott"
- "fareast"
- "fareastboats"
- "farr"
- "maxi"
- "mcconaghy"
- "bakewellwhite"
- "aquarius"
boatDesignOverrides:
- designId: "sydney36mkii"
  canonicalName: "Sydney 36 MkII"
  boats:
  - sailNumber: "5915"
    name: "Stormaway"
    from: null
    until: null
  - sailNumber: "6499"
    name: "Supernova"
    from: null
    until: null
  - sailNumber: "RF360"
    name: "This Way Up"
    from: null
    until: null
- designId: "bashfordsydney36"
  canonicalName: "Bashford Sydney 36"
  boats:
  - sailNumber: "1236"
    name: "LOCAL HERO"
    from: null
    until: null
- designId: "archambaultgrandsurprise"
  canonicalName: "Archambault Grand Surprise"
  boats:
  - sailNumber: "MYC32"
    name: "Esprit"
    from: null
    until: null
  - sailNumber: "M2"
    name: "Remedy"
    from: null
    until: null
  - sailNumber: "N16"
    name: "Bazinga"
    from: null
    until: null
  - sailNumber: "1919"
    name: "Lost Horizon"
    from: null
    until: null
- designId: "archambaultsurprise"
  canonicalName: "Archambault Surprise"
  boats:
  - sailNumber: "6750"
    name: "Asterix"
    from: null
    until: null
- designId: "etchells"
  canonicalName: "Etchells"
  boats:
  - sailNumber: "1161"
    name: "Wildlife"
    from: null
    until: null
- designId: "farr36modified"
  canonicalName: "Farr 36 Modified"
  boats:
    - sailNumber: "1088"
      name: "Corum"
      from: null
      until: null
